clarifai model local-runner
[INFO] 13:32:33.062920 > Checking local runner requirements... |  thread=8800297152 
[INFO] 13:32:33.085516 Checking 1 dependencies... |  thread=8800297152 
[INFO] 13:32:33.085856 ✅ All 1 dependencies are installed! |  thread=8800297152 
[INFO] 13:32:33.086091 > Verifying local runner setup... |  thread=8800297152 
[INFO] 13:32:33.086140 Current context: default |  thread=8800297152 
[INFO] 13:32:33.086179 Current user_id: alfrick |  thread=8800297152 
[INFO] 13:32:33.086210 Current PAT: d6570**** |  thread=8800297152 
[INFO] 13:32:33.088226 Current compute_cluster_id: local-runner-compute-cluster |  thread=8800297152 
[WARNING] 13:32:34.747258 Failed to get compute cluster with ID 'local-runner-compute-cluster':
code: CONN_DOES_NOT_EXIST
description: "Resource does not exist"
details: "ComputeCluster with ID \'local-runner-compute-cluster\' not found. Check your request fields."
req_id: "sdk-python-11.8.2-941866be231e4602865a64d15e01fa55"
 |  thread=8800297152 
Compute cluster not found. Do you want to create a new compute cluster alfrick/local-runner-compute-cluster? (y/n): y
[INFO] 13:32:39.352840 Compute Cluster with ID 'local-runner-compute-cluster' is created:
code: SUCCESS
description: "Ok"
req_id: "sdk-python-11.8.2-eae3c965f0cd4cd394ad2590b47a68ab"
 |  thread=8800297152 
[INFO] 13:32:39.364816 Current nodepool_id: local-runner-nodepool |  thread=8800297152 
[WARNING] 13:32:42.674651 Failed to get nodepool with ID 'local-runner-nodepool':
code: CONN_DOES_NOT_EXIST
description: "Resource does not exist"
details: "Nodepool not found. Check your request fields."
req_id: "sdk-python-11.8.2-436a10af775346878416c84dd6854254"
 |  thread=8800297152 
Nodepool not found. Do you want to create a new nodepool alfrick/local-runner-compute-cluster/local-runner-nodepool? (y/n): y
[INFO] 13:32:45.824647 Nodepool with ID 'local-runner-nodepool' is created:
code: SUCCESS
description: "Ok"
req_id: "sdk-python-11.8.2-0e520dbecfcd42d58fd78b2494c48aa8"
 |  thread=8800297152 
[INFO] 13:32:45.836876 Current app_id: local-runner-app |  thread=8800297152 
[INFO] 13:32:46.896228 Current model_id: local-runner-model |  thread=8800297152 
[WARNING] 13:32:52.596471 Attempting to patch latest version: 9d38bb9398944de4bdef699835f17ec9 |  thread=8800297152 
[INFO] 13:32:55.120866 Successfully patched version 9d38bb9398944de4bdef699835f17ec9 |  thread=8800297152 
[INFO] 13:32:55.124102 Current model version 9d38bb9398944de4bdef699835f17ec9 |  thread=8800297152 
[WARNING] 13:32:56.851018 Failed to get runner with ID 'b3632320627341fb9ea1132d5b77b26f':
code: CONN_DOES_NOT_EXIST
description: "Resource does not exist"
details: "Runner not found. Check your request fields."
req_id: "sdk-python-11.8.2-0988ef3bd3144e0196cff79062621406"
 |  thread=8800297152 
[INFO] 13:32:56.851708 Creating the local runner tying this 'alfrick/local-runner-app/models/local-runner-model' model (version: 9d38bb9398944de4bdef699835f17ec9) to the 'alfrick/local-runner-compute-cluster/local-runner-nodepool' nodepool. |  thread=8800297152 
[INFO] 13:32:57.321664 Runner with ID 'f3c46913186449ba99dedd38123d47a3' is created:
code: SUCCESS
description: "Ok"
req_id: "sdk-python-11.8.2-8ec4cb69afdb402cb173e50251420347"
 |  thread=8800297152 
[INFO] 13:32:57.331723 Current runner_id: f3c46913186449ba99dedd38123d47a3 |  thread=8800297152 
[WARNING] 13:32:57.624714 Failed to get deployment with ID local-runner-deployment:
code: CONN_DOES_NOT_EXIST
description: "Resource does not exist"
details: "Deployment with ID \'local-runner-deployment\' not found. Check your request fields."
req_id: "sdk-python-11.8.2-93d203f6c0c944e5a844967a7f6f3c9b"
 |  thread=8800297152 
Deployment not found. Do you want to create a new deployment alfrick/local-runner-compute-cluster/local-runner-nodepool/local-runner-deployment? (y/n): y
[INFO] 13:33:00.896305 Deployment with ID 'local-runner-deployment' is created:
code: SUCCESS
description: "Ok"
req_id: "sdk-python-11.8.2-68917fcd0d3c403db684a06a417d804e"
 |  thread=8800297152 
[INFO] 13:33:00.904547 Current deployment_id: local-runner-deployment |  thread=8800297152 
[INFO] 13:33:00.907140 Current model section of config.yaml: {'id': 'my-uploaded-model', 'user_id': 'alfrick', 'app_id': 'models1', 'model_type_id': 'text-to-text'} |  thread=8800297152 
Do you want to backup config.yaml to config.yaml.bk then update the config.yaml with the new model information? (y/n): y
[INFO] 13:33:03.816163 Checking 1 dependencies... |  thread=8800297152 
[INFO] 13:33:03.816702 ✅ All 1 dependencies are installed! |  thread=8800297152 
[INFO] 13:33:03.816783 ✅ Starting local runner... |  thread=8800297152 
[INFO] 13:33:03.816865 No secrets path configured, running without secrets |  thread=8800297152 
[INFO] 13:33:05.775735 ModelServer initialized successfully |  thread=8800297152 
Exception in thread Thread-1 (serve_health):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.11/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.12/3.12.11/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/macbookpro/Desktop/code/venv/lib/python3.12/site-packages/clarifai_protocol/utils/health.py", line 67, in serve_health
  File "/opt/homebrew/Cellar/python@3.12/3.12.11/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/opt/homebrew/Cellar/python@3.12/3.12.11/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/opt/homebrew/Cellar/python@3.12/3.12.11/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use
[INFO] 13:33:05.827501 ✅ Your model is running locally and is ready for requests from the API...
 |  thread=8800297152 
[INFO] 13:33:05.827575 > Code Snippet: To call your model via the API, use this code snippet:
# Clarifai Model Client Script
# Set the environment variables `CLARIFAI_DEPLOYMENT_ID` and `CLARIFAI_PAT` to run this script.
# Example usage:
import os

from clarifai.client import Model
from clarifai.runners.utils import data_types

model = Model(
    "https://clarifai.com/alfrick/local-runner-app/models/local-runner-model",
    deployment_id='local-runner-deployment',  # Only needed for dedicated deployed models
    base_url="https://api.clarifai.com",
)

# Example model prediction from different model methods:

response = model.predict(
    text1="What is the future of AI?",
)
print(response)

response = model.generate(
    text1="What is the future of AI?",
)
for res in response:
    print(res)

response = model.stream(
    input_iterator=iter(['What is the future of AI?']),
)
 |  thread=8800297152 
[INFO] 13:33:05.827661 > Playground:   To chat with your model, visit: https://clarifai.com/playground?model=local-runner-model__9d38bb9398944de4bdef699835f17ec9&user_id=alfrick&app_id=local-runner-app
 |  thread=8800297152 
[INFO] 13:33:05.827704 > API URL:      To call your model via the API, use this model URL: https://clarifai.com/alfrick/local-runner-app/models/local-runner-model
 |  thread=8800297152 
[INFO] 13:33:05.827724 Press CTRL+C to stop the runner.
 |  thread=8800297152 
[INFO] 13:33:05.827758 Starting 32 threads... |  thread=8800297152 
